### PR TITLE
Feature/database api examples

### PR DESCRIPTION
**Pull request by andyjohns**

### CODE REVIEW

**Comment by jeremyosterhoudt** [comment]
Looks good but I did run into one issue.  When I open the workspace the Database example project is not found.  

When I add the project manually everything is in working order.  Please see the image below:

screen shot 2018-01-26 at 1 37 26 pm

**Comment by andyjohns** [comment]
That's really weird, as everything definitely appears on my machine. I added shared schemes for those projects, maybe that had something to do with it.

**Comment by andyjohns** [comment]
Ah, got it. There was a bad group reference in the workspace. Fixed.... Please confirm

**Comment by jeremyosterhoudt** [comment]
👍 Approved.

**Pull request merged**
